image:
  file: .gitpod.Dockerfile
tasks:
  - init: python3 -m pip install -r requirements-dev.txt
    command: /workspace/.pip-modules/bin/mkdocs serve --dev-addr 0.0.0.0:8000
vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter
    - ms-python.python
    - hbenl.test-adapter-converter
    - rvest.vs-code-prettier-eslintports
ports: 
  - port: 8000
    onOpen: open-preview