image:
  file: .gitpod.Dockerfile
tasks:
  - init: pip install -r requirements-dev.txt
vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==
    - ms-python.python
