image:
  file: .gitpod.Dockerfile
tasks:
  - init: pip install -r requirements-dev.txt
    command: /workspace/.pip-modules/bin/mkdocs serve --dev-addr 0.0.0.0:8000
vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==
    - ms-python.python
    - hbenl.test-adapter-converter
    - matangover.mypyports:
  - port: 8000
    onOpen: open-preview
