version: 2.1
orbs:
  python: circleci/python@1.4.0
  git: opuscapita/git@0.0.3
  coveralls: coveralls/coveralls@1.0.6
jobs:
  unittests:
    executor: python/default
    steps:
      - git/checkout-with-submodules
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements-dev.txt
          pkg-manager: pip
      - run:
          command: |
            pytest --cov
          name: Test
      - coveralls/upload
workflows:
  main:
    jobs:
      - unittests