version: 2.1
orbs:
  python: circleci/python@1.4.0
jobs:
  unittests:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements-dev.txt
          pkg-manager: pip
      - run:
          command: |
            pytest
          name: Test
workflows:
  main:
    jobs:
      - unittests