version: 2.1
orbs:
  python: circleci/python@1.4.0
  git: opuscapita/git@0.0.3
  coveralls: coveralls/coveralls@1.0.6
jobs:
  unittests_3_5:
    executor:
      name: python/default
      tag: "3.5"
    steps:
      - git/checkout-with-submodules
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
      - run:
          command: |
            pytest --junitxml=/tmp/testresults.xml
          name: Test
      - store_test_results:
          path: /tmp/testresults.xml
  unittests_3_9:
    executor:
      name: python/default
      tag: "3.9"
    steps:
      - git/checkout-with-submodules
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pkg-manager: pip
          args: pytest-cov
      - python/install-packages:
          pip-dependency-file: requirements-dev.txt
          pkg-manager: pip
      - run:
          command: |
            pytest --cov --junitxml=/tmp/testresults.xml
          name: Test
      - store_test_results:
          path: /tmp/testresults.xml
      - coveralls/upload
workflows:
  main:
    jobs:
      - unittests_3_5
      - unittests_3_9